server:
  port: 8761
eureka:
  datacenter: trmap
  environment: product
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://root:booszy@localhost:8761/eureka
    #关闭自己作为客户端注册
    register-with-eureka: false
    fetch-registry: false
security:
  basic:
    enabled: true
  user:
    #用户名和密码，等会访问的时候，会要求你登录，服务注册的时候也需要带着用户名和密码
    name: root
    password: root