server:
  port: 8800
eureka:
  client:
    service-url:
#      defaultZone: http://root:booszy@172.17.0.1:8761/eureka
      defaultZone: http://root:root@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    appname: bf-sc-config-server
spring:
  application:
    name: bf-sc-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhg0914/bf-sc-1.0.git
          searchPaths: bf-sc-config-repository
security:
  basic:
    enabled: true
  user:
    name: root
    password: root